name: "publish package to npm"

on: push

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - name: Install dependencies
      run: npx ci
    - name: Install semantic-release extra plugins
      run: npm install --save-dev @semantic-release/changelog @semantic-release/git      
    - name: Build
      run: npm run build      
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPMAUTHTOKEN }}
      run: npx semantic-release
  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2
  #     - name: node
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         registry-url: https://registry.npmjs.org
  #     - name: publish
  #       run: npm publish --access public
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.NPMAUTHTOKEN}}